[workspace]
members = ["projects/*"]
default-members = [
    "projects/vos-from-json-schema",
    "projects/vos-from-protobuf",
    "projects/vos-into-rust-flexbuffer",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
